### ISSUE TITLE
 NoMethodError: undefined method `perform_step' for Integrations::Dummy:Module

### ISSUE THREAD

**Issue by Skeyelab** [joelmoss/sidekiq-sequence#10]
I seem to be running into a similar issue as [this](https://github.com/joelmoss/sidekiq-sequence/issues/4) one.

The first step runs fine, but then I get this error.

```
2022-08-04T16:24:34.411Z 81048 TID-13oj618 WARN: NoMethodError: undefined method `perform_step' for Integrations::Dummy:Module
2022-08-04T16:24:34.411Z 81048 TID-13oj618 WARN: /Users/eric.dahl/.rvm/gems/ruby-2.6.9@provi-integrations/gems/sidekiq-sequence-0.1.10/lib/sidekiq/sequence/perform.rb:19:in `perform'
```

My files are 
- /app/workers/integrations/dummy/assign_message.rb
- /app/workers/integrations/dummy/create_message.rb
- /app/workers/integrations/dummy/test_sequence.rb

Here is my sequence:
```
module Integrations
  module Dummy
    class TestSequence < Sidekiq::Sequence::Base
      step CreateMessage
      # step AssignMessage
    end
  end
end
```

Here is my first step:
```
module Integrations
  module Dummy
    class CreateMessage
      include Sidekiq::Sequence::Worker

        def perform
          puts 'data: '
          puts @data
          (1..5).each do |a|
            puts "Creating Message: #{a}"
            sleep 1
          end
      end
    end
  end
end
```

**Comment by joelmoss** [comment]
Your step classes need to be subclasses of your Sequence class.

So with a sequence class of `Integrations::Dummy::TestSequence`, your step classes would be something like `Integrations::Dummy::TestSequence::CreateMessage`.

Your example showed your step class as `Integrations::Dummy::CreateMessage` - not a subclass of `Integrations::Dummy::TestSequence`.

**Comment by Skeyelab** [comment]
@joelmoss so when I change the step to be like so:

```
module Integrations
  module Dummy
    class TestSequence::CreateMessage
      include Sidekiq::Sequence::Worker

        def perform
          puts 'data: '
          puts @data
          (1..5).each do |a|
            puts "Creating Message: #{a}"
            sleep 1
          end
      end
    end
  end
end
```
I get:

```
/Users/eric.dahl/.rvm/gems/ruby-2.6.9@provi-integrations/gems/activesupport-6.0.4.8/lib/active_support/dependencies.rb:555:in `load_missing_constant': Unable to autoload constant Integrations::Dummy::CreateMessage, expected /Users/eric.dahl/Documents/GitHub/provi-integrations/app/workers/integrations/dummy/create_message.rb to define it (LoadError)
```

**Comment by joelmoss** [comment]
Still sounds like you have things named/placed incorrectly. At least that is what that error implies.

**Comment by Skeyelab** [comment]
BOOM! 

It worked!  Thank you so much

**Comment by joelmoss** [comment]
> maybe this could be a little clearer in the doc?

That's actually nothing to do with this gem - it's a Ruby thing that applies to all your Ruby code.

Anyway, glad you got it working 👍
