### ISSUE TITLE
Using the DB to determine the steps

### ISSUE THREAD

**Issue by ivorpad** [joelmoss/sidekiq-sequence#12]
Can the database be used to determine steps? I have a workflow object that has many steps and I want them to run sequentially.

Here is some pseudo code of what I'm trying to accomplish:

```ruby
workflows  = Workflow.preload(:steps).last

steps.order(:position).each do |step|
  step_name = step.name.capitalize
  step "#{step_name}Step".constantize
end
```

**Comment by joelmoss** [comment]
That would be quite a change to the way things work right now, but no less interesting.

I suppose my first question, is why?

**Comment by ivorpad** [comment]
@joelmoss workflow & automation sequencing.

Imagine a UI with drag & drop where the user can determine which sequence run first. Your gem would be _very_ useful in this scenario.

These type of UIs can be used for literally anything:

- Drip campaigns automation for abandoned carts, first purchases etc.
- When reviewing PRs in a team, I can create a workflow that delays one day, sends an email if reviewers don't act, delays two days, perform other actions.

## Example:
![Screenshot 2022-08-05 at 15 46 39](https://user-images.githubusercontent.com/52452/183090415-4b94fce9-51fe-4ace-92b9-c5ed441b6d11.png)

I can try making the changes if you point me in the right direction.

**Comment by joelmoss** [comment]
OK, so you want a dynamically defined sequence?

Should be possible, but one place where I can see some issues/complexity, is when the sequence is modified while steps are in progress.

Happy to accept a PR. Shout if you have any questions.
