### ISSUE TITLE
NameError: uninitialized constant but worker is called

### ISSUE THREAD

**Issue by Trimakas** [joelmoss/sidekiq-sequence#23]
This feels like a gem issue, but I'm not sure as I have this exact same code working in another app. But for some reason I'm getting `NameError: uninitialized constant OverallProductSync` 

And I'm calling this via a `step` defined like this:
```
class OverallProductSync < Sidekiq::Sequence::Base

  step OverallProductSync::GetShopifyProductWorker
  step OverallProductSync::SyncAmazonProductWorker

end
```

The interesting thing is that when I put a `byebug` into one of those workers before the `perform` it does get hit. Like this:

```
class OverallProductSync::GetShopifyProductWorker
  include Sidekiq::Sequence::Worker

  sidekiq_options queue: :product_sync

  byebug

  def perform
    shop = Shop.find(@data["shop_id"])
    GetShopifyProductDataService.call(shop)
  end

end
```

But if I place it inside of the `perform` it does not get hit, and the error is thrown.

I'm using the following gems:

```
  * sidekiq (6.5.6)
  * sidekiq-sequence (0.2.1)
  * bundler (2.3.25)
```

And finally my folder structure looks like this:

- workers/overall_product_sync.rb
- workers/overall_product_sync/get_shopify_product_worker.rb
- workers/overall_product_sync/sync_amazon_product_worker.rb

Seen this before?

EDIT:
Even more odd is that I hit those byebugs and it just waited for a good couple minutes, but then when I came back and let it run, it actually did run..

**Comment by joelmoss** [comment]
Try this

```ruby
class OverallProductSync < Sidekiq::Sequence::Base
  step GetShopifyProductWorker
  step SyncAmazonProductWorker
end
```

**Comment by Trimakas** [comment]
@joelmoss shoot.. no, same thing

**Comment by joelmoss** [comment]
Can you create a test app in a GH repo with this code, that reproduces the issue please? thx

**Comment by Trimakas** [comment]
Wow, I basically rebuilt the app, with a fresh set of gems and configs. After all that its working like a champ! Sorry for the bother, and thanks for the gem @joelmoss !!
