### ISSUE TITLE
Is there anyway to stop the steps?

### ISSUE THREAD

**Issue by Trimakas** [joelmoss/sidekiq-sequence#28]
I'm trying a well placed `return` but it's not working.. So the idea is I have a list of steps, with the first step pulling a report. However, if nothing is in the report, then nothing else needs to happen.

So is there a way to stop the `steps` after a no response?

Thanks!

**Comment by joelmoss** [comment]
There isn't a built-in way to do that, but it can be easily achieved by setting a data attribute. So in any step, assign some data value:

```ruby
def perform
  @data[:complete] = true
end
```

Then in later steps you can add a guard for this

```ruby
def perform
  return if @data[:complete]

  # ... perform next step here
end
```

**Comment by Trimakas** [comment]
Awesome! Thanks man.. yea was slowly getting there..
