### ISSUE TITLE
Serialize models using GlobalID

### ISSUE THREAD

**Issue by adambedford** [joelmoss/sidekiq-sequence#3]
First off, thanks for making this library! Just came across it looking for a way to control the sequence of jobs and I think this will do the trick.

One nuance we'll have to code around for now is that ActiveRecord objects get serialized as a HashWithIndifferentAccess by the looks of things, whereas I was expected to get the model record back. Please do let me know if it sounds like I'm doing something wrong though! It would be awesome if this library used GlobalID to (de)serialize job arguments.

**Comment by joelmoss** [comment]
Well this is designed for arbitrary data, and not specifically AR records, so all data it reads and writes is simply a hash, serialized as JSON in the `sidekiq_sequence_record` DB table using `ActiveRecord::Base.serialize`.

I wouldn't recommend you store model data, as that could out of sync with the actual model data. Instead, simply store model ID's in `@data`.

```ruby
@data[:user_id] = 102
```

Then look up the record when needed. That way, you are always reading data from the source of truth - the model.

But I see no reason why GlobalID couldn't be used. PR's are welcome 😉
